name: calc_cientifica_estrella
description: Calculadora Científica CETIS 131 — Valentina Carrizales Flores
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_cetis.jpg
